### ISSUE TITLE
Unknown error on Arch linux

### ISSUE THREAD

**Issue by 0xrushi** [confident-hate/seedr-cli#13]
```
└─$ seedr       
Unknown error...
```

**Comment by confident-hate** [comment]
Issue fixed with [this ](https://github.com/confident-hate/seedr-cli/commit/1c86b27ac4aea1590e949f77673c625ee50160cb)commit. Test it now.

**Comment by 0xrushi** [comment]
@confident-hate nop, still same

**Comment by confident-hate** [comment]
> @confident-hate nop, still same

Try using it via this command `└─$ python main.py -h` instead of `└─$ seedr -h`.

**Comment by 0xrushi** [comment]
└─$ python main.py   
Unknown error...

**Comment by confident-hate** [comment]
As you can see is [this](https://i.imgur.com/pI0XApt.png) screenshot that it is working in arch linux. You should try commenting out `except` block in main.py file line number 471 to 473. Then run and it will tell you exact problem.
